"""
Django settings for wazi project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config
import os
import base64
from cryptography.fernet import Fernet

# print("FERNET KEY",Fernet.generate_key())


# print("Omaria",os.path.abspath(os.path.dirname(__name__)))

# new_key = base64.urlsafe_b64encode(os.urandom(32))
# print(new_key)


# if os.name == "nt":
#     import platform

#     OSGEO4W = r"C:\OSGeo4W"
#     if "64" in platform.architecture()[0]:
#         OSGEO4W
#     assert os.path.isdir(OSGEO4W), "Directory does not exist: " + OSGEO4W
#     os.environ["OSGEO4W_ROOT"] = OSGEO4W
#     os.environ["GDAL_DATA"] = OSGEO4W + r"\share\gdal"
#     os.environ["PROJ_LIB"] = OSGEO4W + r"\share\proj"
#     os.environ["PATH"] = OSGEO4W + r"\bin;" + os.environ["PATH"]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent
# import os
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = '0(#7r2#25&2l-ug_8$0lxqis-0p!mj3ihj-ogcsz_j&%0wro*s'

# # SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG")
CELERY_IMPORT = ['properties.tasks', 'employees.tasks', 'distributors.tasks', 'hospitals.tasks', 'drugs.tasks', 'loyalty.tasks', 'logistics.tasks', 'messaging.tasks', 'manufacturers.tasks', 'payments.tasks', 'products.tasks', 'parking.tasks', 'retailers.tasks', 'services.tasks', 'saccos.tasks', 'expenses.tasks', 'transport.tasks', 'restaurants.tasks', 'wholesalers.tasks', 'wifi.tasks', 'subscriptions.tasks', 'chats.tasks', 'stats.tasks', 'ussd.tasks']


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")
FIELD_ENCRYPTION_KEY  = config("FIELD_ENCRYPTION_KEY")
ENCRYPT_KEY=config("ENCRYPT_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = config("DEBUG")
# DEVELOPMENT_MODE = config("DEVELOPMENT_MODE")

ALLOWED_HOSTS = ["*",'24b2-102-219-248-21.ngrok-free.app']

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
# Application definition
# DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880 # 5 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    'rest_framework.authtoken',
    'dj_rest_auth',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth.registration',
    "rest_framework_api_key",
     "channels",
    "django_celery_beat",
    "django_celery_results",
    "encrypted_model_fields",
    "authentication",
    "django.contrib.sites",
    "corsheaders",
    "drf_yasg",
    "django.contrib.gis",
    "rest_framework_gis", 
    "django_advance_thumbnail",
    "cities_light",
    "subscriptions",
    "hospitals",
    "hotspots",
    "distributors",
    "drugs",
    "entitylocations",
    "employees",
    "loyalty",
    "logistics",
    "messaging",
    "manufacturers",
    "payments",
    "products",
    "parking",
    "retailers",
    "services",
    "saccos",
    "expenses",
    "properties",
    "transport",
    "restaurants",
    "wholesalers",
    "wifi",
    "chats",
    "stats",
    "ussd",
   
]



AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
  
    "authentication.backends.UserNamePhoneAuthBackend",
)

MIDDLEWARE = [
     "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
     "allauth.account.middleware.AccountMiddleware",
     'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = "wazi.urls"

# STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wazi.wsgi.application"

# Configuration for django channela
ASGI_APPLICATION = "wazi.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [("127.0.0.1", 6379)]},
    }
}


# Database


DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASS"),
        "HOST": config("DB_HOST"),
        "PORT": config("PG_PORT"),
        "CONN_MAX_AGE": None,
    },
     'radius': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'radius_db',                  # Your newly created RADIUS database
        'USER': 'radius_admin',               # The user we just created
        'PASSWORD': config("DB_PASS"), # The password you set in psql
        'HOST': config("DB_HOST"),                 # Use 'localhost' or server IP
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Nairobi"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# settings.py

DATABASE_ROUTERS = ['wazi.settings.routers.RadiusRouter']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"
# PROJECT_ROOT = os.path.join(os.path.abspath(__file__))
# PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles')
# STATIC_ROOT = os.path.join(PROJECT_ROOT, config("STATIC_ROOT"))
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# STATIC_URL = config("STATIC_URL")

MEDIA_ROOT = os.path.join(BASE_DIR, config("MEDIA_ROOT"))
MEDIA_URL = config("MEDIA_URL")

SITE_ID = 3
AUTH_USER_MODEL = "authentication.Users"


# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, 'staticfiles'),
# )
# STATICFILES_DIRS = [
#     BASE_DIR.joinpath('static')
# ]

# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

FIXTURES_DIRS = (os.path.join(BASE_DIR, "fixtures"),)

LOCATION_FIELD = {
    "map.provider": "google",
    "map.zoom": 13,
    "search.provider": "google",
    "search.suffix": "",
    # Google
    "provider.google.api": "//maps.google.com/maps/api/js",
    "provider.google.api_key": "",
    "provider.google.map_type": "ROADMAP",
    # Mapbox
    "provider.mapbox.access_token": "",
    "provider.mapbox.max_zoom": 18,
    "provider.mapbox.id": "mapbox.streets",
    # OpenStreetMap
    "provider.openstreetmap.max_zoom": 18,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "SIGNING_KEY": config("SECRET_KEY"),
    "VERIFYING_KEY": config("SECRET_KEY"),
}

REST_AUTH = {
    "USE_JWT": True,
    # "JWT_AUTH_COOKIE": "_auth",  # Don't send access token cookie
    # "JWT_AUTH_REFRESH_COOKIE": "_refresh", # Don't send refresh token cookie
    "JWT_AUTH_HTTPONLY": False,  # Makes sure refresh token is sent
}

REST_FRAMEWORK = {
    # "DEFAULT_PAGINATION_CLASS": "core.pagination.CustomPagination",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "EXCEPTION_HANDLER": "utils.exceptionhandler.custom_exception_handler",
    "PAGE_SIZE": 10000,
    "NON_FIELD_ERRORS_KEY": "error",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",
    "DEFAULT_FILTER_BACKENDS": (
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "SEARCH_PARAM": "q",
    "ORDERING_PARAM": "ordering",
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser'
     )
}

# Sending email
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# EMAIL_HOST_USER = config("EMAIL_HOST_USER2")
# EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD2")
# EMAIL_HOST_PASSWORD = ''




ACCOUNT_EMAIL_VERIFICATION = "none" # Do not require email confirmation
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = "email"


# Google OAuth
GOOGLE_OAUTH_CLIENT_ID = config("GOOGLE_OAUTH_CLIENT_ID")
GOOGLE_OAUTH_CLIENT_SECRET = config("GOOGLE_OAUTH_CLIENT_SECRET")
GOOGLE_OAUTH_CALLBACK_URL = config("GOOGLE_OAUTH_CALLBACK_URL")


# django-allauth (social)
# Authenticate if local account with this email address already exists
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
# Connect local account and social account if local account with that email address already exists
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APPS": [
            {
                "client_id": GOOGLE_OAUTH_CLIENT_ID,
                "secret": GOOGLE_OAUTH_CLIENT_SECRET,
                "key": "",
            },
        ],
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    }
}

CORS_ORIGIN_ALLOW_ALL = True
CSRF_TRUSTED_ORIGINS = [
    "https://wazipos.co.ke",
    "https://api.wazipos.co.ke",
    "http://127.0.0.1:8000",
     "https://api.jambopay.com",
      "http://localhost:5173",
      "http://localhost:8081",
     
]


CORS_ORIGIN_WHITELIST = ("http://localhost:3000",)

CORS_ALLOWED_ORIGINS = [
    "https://wazipos.co.ke",
     "http://localhost:5173",
     "http://localhost:8081",
]
# Celery Broker - Redis
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = "django-db"
CELERY_ENABLE_UTC = True
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Africa/Nairobi"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True


LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "entity_admin"
# Everything goes by https, except the transport app urls that goes on http

SECURE_REDIRECT_EXEMPT = ["transport"]


INTERNAL_IPS = [
    "127.0.0.1",
]


import logging
import logging.config
from django.utils.log import DEFAULT_LOGGING
logger = logging.getLogger(__name__)

LOG_LEVEL ="INFO"

logging.config.dictConfig({
    "version":1,
    "disable_existing_loggers":False,
    "formatters":{
        "console":{
            "format":"%(asctime)s %(name)-12s %(levelname)-8s %(message)s"
        },
        "file":{"format":"%(asctime)s %(name)-12s %(levelname)-8s %(message)s"},
        "django.server": DEFAULT_LOGGING["formatters"]["django.server"],
    },
    "handlers":{
        "console":{
            "class":"logging.StreamHandler",
            "formatter":"console"
        },
        "file":{
            "level":"INFO",
            "class":"logging.FileHandler",
            "formatter":"file",
            "filename":"logs/wazi.log"
        },
        "django.server": DEFAULT_LOGGING["handlers"]["django.server"],
    },
    "loggers":{
        "":{"level":"INFO", "handlers":["console","file"],"propagate":False},
        "apps":{
            "level":"INFO","handlers":["console"],"propagate":False
        },
         "django.server": DEFAULT_LOGGING["loggers"]["django.server"],
         'daphne': {
    'handlers': [
        'console',
    ],
    'level': 'DEBUG'
}
    }
})