import { useAuth } from '@/context/AuthContext';
import { useInventorySync } from '@/context/InventorySyncContext';
import { DatabaseEngine } from '@/databases/db';
import React, { useMemo, useRef } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import CustomerOrderBarcodeScannerTrigger from './CustomerOrdeScannerTrigger';
import OrderLineCard from './OrderLineCard';
import OrderSummaryPane from "./OrderSummaryPane";
import { useUniversalOrderCreator } from './useUniversalOrderCreator';
export default function UniversalOrderCreator({ onSubmitOrder }: any) {
    const { theme, user } = useAuth(), { isSyncing, triggerManualFetch, lastSyncedTime, retailerReceipts } = useInventorySync(), ctx = useUniversalOrderCreator(user || { id: 'unknown_vendor' }, onSubmitOrder), refs = useRef<any>({}), blank = useMemo(() => ctx.lineItems && ctx.lineItems.some((i: any) => i.selectedProduct === null), [ctx.lineItems]), handleSelect = (prod: any, fn: any) => { const bp = Number(prod.unit_selling_price || prod.price || 0); ctx.setLineItems((prev: any[]) => { let next = [...prev]; const idx = prev.findIndex(i => { try { const p = typeof i.selectedProduct === 'string' ? JSON.parse(i.selectedProduct) : i.selectedProduct; return p && (p.id === prod.id || p.key === prod.key); } catch { return i.selectedProduct === prod.key; } }); if (idx > -1) { next[idx].quantity = (next[idx].quantity || 1) + 1; } else if (prev.length === 1 && !prev.selectedProduct && !prev.selectedProductTitle) { next = [{ id: prev.id || "1", selectedProduct: JSON.stringify(prod), selectedProductTitle: String(prod.title || prod.product_name || ""), quantity: 1, price: bp, unit_selling_price: String(bp.toFixed(2)), final_unit_selling_price: String(bp.toFixed(2)), discount: 0, searchQuery: String(prod.title || prod.product_name || ""), isDropdownOpen: false }]; } else { next = [...prev, { id: String(Math.max(0, ...prev.map(i => Number(i.id) || 0)) + 1), selectedProduct: JSON.stringify(prod), selectedProductTitle: String(prod.title || prod.product_name || ""), quantity: 1, price: bp, unit_selling_price: String(bp.toFixed(2)), final_unit_selling_price: String(bp.toFixed(2)), discount: 0, searchQuery: String(prod.title || prod.product_name || ""), isDropdownOpen: false }]; } try { DatabaseEngine.saveLineItems(next); } catch { } return next; }); }; return (<SafeAreaView style={{ backgroundColor: theme.background }} className="flex-1 w-full relative">{ctx.showSuccessBanner && (
        <View style={{ backgroundColor: theme.panel, borderColor: '#10b981', zIndex: 99999 }} className="absolute top-6 left-6 right-6 p-4 rounded-2xl border-2 shadow-2xl flex-row items-center gap-x-4">
            <View className="w-10 h-10 bg-emerald-500/10 rounded-full items-center justify-center border border-emerald-500/20"><Text style={{ fontFamily: theme.font.bold }} className="text-emerald-500 text-base font-black">✓</Text></View>
            <View className="flex-1 flex-col"><Text style={{ fontFamily: theme.font.bold, fontSize: theme.fontSize.base, color: theme.text }} className="font-black tracking-tight">Order Saved to Remote Cloud</Text><Text style={{ fontFamily: theme.font.mono, fontSize: 11, color: theme.textDark }} className="opacity-70 mt-0.5 uppercase">Server Gateway Ref: #{ctx.bannerRefCode}</Text></View>
        </View>)}
        <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ padding: 16 }} className="w-full lg:max-w-[80vw] lg:mx-auto space-y-4" keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={isSyncing} onRefresh={triggerManualFetch} colors={[theme.primary]} tintColor={theme.primary} />}>
            <View className="w-full flex flex-col md:flex-row justify-between items-start md:items-center pb-4 mb-6 border-b border-slate-200 dark:border-slate-800 gap-y-4 md:gap-y-0 min-h-[64px] relative z-40">
                <View className="flex-col flex-1 min-w-0 pr-6"><View className="flex-row items-center flex-wrap gap-x-2.5 gap-y-1"><Text style={{ fontFamily: theme.font.bold, fontSize: theme.fontSize.xl, color: theme.text }} className="tracking-tight font-black">New Customer Order</Text>{isSyncing ? (
                    <View className="flex-row items-center bg-blue-500/10 px-2 py-0.5 rounded-md gap-x-1"><ActivityIndicator size="small" color={theme.primary} style={{ transform: [{ scale: 0.7 }] }} /><Text style={{ color: theme.primary, fontFamily: theme.font.bold, fontSize: theme.fontSize.xs }} className="font-bold tracking-widest uppercase">Syncing</Text></View>) : lastSyncedTime ? (
                        <View className="bg-emerald-500/10 px-2 py-0.5 rounded-md"><Text style={{ color: '#10b981', fontFamily: theme.font.bold, fontSize: theme.fontSize.xs }} className="font-bold uppercase tracking-wider">🕒 Synced {lastSyncedTime}</Text></View>) : null}</View><Text style={{ fontFamily: theme.font.medium, fontSize: theme.fontSize.xs, color: theme.textDark }} className="mt-1 font-medium text-slate-500 dark:text-slate-400">Generate checkout indents and register inventory lines</Text></View>
                <View className="w-full md:w-auto min-w-0 md:min-w-[320px] lg:min-w-[420px] items-stretch md:items-end"><CustomerOrderBarcodeScannerTrigger theme={theme} onScanSuccess={(sku) => { const p = retailerReceipts?.find((r: any) => r.sku === sku || r.bar_code === sku || r.barcode === sku); if (p) handleSelect(p, ctx.setLineItems); }} /></View>
            </View>
            <View className="flex-col lg:flex-row gap-4 items-start relative z-10 w-full">
                <View className="flex-1 space-y-3 w-full z-30">{ctx.lineItems && ctx.lineItems.map((item: any) => (
                    <OrderLineCard key={item.id} item={item} theme={theme} allLineItems={ctx.lineItems} qtyInputRefs={refs} inventoryPool={retailerReceipts || []} onUpdate={(u: any) => { if (u.selectedProduct) { const p = typeof u.selectedProduct === 'string' ? JSON.parse(u.selectedProduct) : u.selectedProduct; const bp = Number(p.unit_selling_price || p.price || 0); u.price = bp; u.unit_selling_price = String(bp.toFixed(2)); u.final_unit_selling_price = String(bp.toFixed(2)); } ctx.updateLineItem(item.id, u); }} onDelete={() => ctx.handleDeleteItem(item.id)} />))}
                    <TouchableOpacity disabled={blank} onPress={ctx.handleAddNewItem} style={{ borderColor: blank ? '#cbd5e1' : theme.primary }} className={`w-full h-11 border border-dashed rounded-xl items-center justify-center transition-all ${blank ? 'opacity-40 bg-slate-100/50 dark:bg-slate-800/20' : 'bg-transparent active:bg-slate-50 dark:active:bg-slate-900'}`}><Text style={{ fontFamily: theme.font.bold, fontSize: theme.fontSize.sm, color: blank ? theme.textDark : theme.primary }}>+ Add Another Product Line</Text></TouchableOpacity>
                </View>
                <View className="w-full lg:w-[360px] xl:w-[400px] z-20">
                    <OrderSummaryPane theme={theme} customerName={ctx.customerName} setCustomerName={ctx.setCustomerName} customerPhone={ctx.customerPhone} setCustomerPhone={ctx.setCustomerPhone} dueDate={ctx.dueDate} setDueDate={ctx.setDueDate} deliveryMethod={ctx.deliveryMethod} setDeliveryMethod={ctx.setDeliveryMethod} shippingCost={ctx.shippingCost} setShippingCost={ctx.setShippingCost} paymentAccountNumber={ctx.paymentAccountNumber} setPaymentAccountNumber={ctx.setPaymentAccountNumber} selectedPaymentMethodId={ctx.selectedPaymentMethodId} setSelectedPaymentMethodId={ctx.setSelectedPaymentMethodMethodId} computedTotals={ctx.computedTotals} isCredit={ctx.isCredit} isMobileMoney={ctx.isMobileMoney} handleFormSubmission={ctx.handleFormSubmission} isLoading={ctx.isLoading} />
                </View>
            </View>
        </ScrollView>
    </SafeAreaView>);
}
